name: memesflixx
description: A meme-only social platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # UI & assets
  cached_network_image: ^3.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  package_info_plus: ^4.0.0
  cupertino_icons: ^1.0.5
  flutter_app_badger: ^1.3.0
  flutter_local_notifications: ^19.5.0
  video_player: ^2.6.0
  share_plus: ^12.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
